ALTER TABLE users ADD COLUMN password VARCHAR(255) NOT NULL AFTER email;
-- Jika create baru:
CREATE TABLE IF NOT EXISTS users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL
);

ALTER TABLE users
    MODIFY created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    MODIFY updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

CREATE TABLE IF NOT EXISTS products (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    price DECIMAL(12,2) NOT NULL
);

INSERT INTO products (name, price) VALUES
('Product A', 12000),
('Product B', 20000);